### ISSUE TITLE
Support cookies like browsers do

### ISSUE THREAD

**Issue by rogerleite** [rogerleite/http_monkey#3]
Maintain (and uses) cookies through requests.

**Comment by lfcipriani** [comment]
Just to add that we also need a configuration that allows the user to keep cookies or not.

**Comment by rogerleite** [comment]
Started as middleware here: https://github.com/rogerleite/http_monkey-cookie

**Comment by rogerleite** [comment]
[http_monkey-cookie](https://github.com/rogerleite/http_monkey-cookie), is available on rubygems.
