### ISSUE TITLE
Cache?

### ISSUE THREAD

**Issue by igorescobar** [rogerleite/http_monkey#5]
Hi Roger,

First of all, nice work!

Are you willing to implement a feature that "respect" the max-age of the requested file in a way that we can choose where to cache the requested file - like a memcached or something - to intercept the HTTP request before http_monkey does. Would be nice if get started a new thread to discuss about this.
- Igor

**Comment by lfcipriani** [comment]
Hi Igor, this will be implemented by an extension, that later could be used as a middleware in the request-response flow.

There is a initial work here: https://github.com/abril/cachebag

**Comment by igorescobar** [comment]
Hi @lfcipriani sorry but I wasn't talking to you... hahaha just kidding ;P

That's nice! That's what I'm thinking too! Middlewares for the win. Keep rocking ;)

**Comment by rogerleite** [comment]
The idea is to keep monkey "clean" as possible. As you said, "Middlewares for the win!".
